# Generated by Django 4.2.5 on 2023-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='phone_numbers',
            field=models.TextField(default=''),
        ),
    ]
