# Generated by Django 4.2.5 on 2023-10-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_remove_whatsappmessage_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='phone_numbers',
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
